// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sequencestore/v1/sequencestore.proto

package sequencestorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AckStatus reports the outcome of one published entry.
type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	// Appended; head advanced.
	AckStatus_ACK_STATUS_OK AckStatus = 1
	// prefix_commitment != current head — re-read the tail via the consumer
	// API, rebuild, then publish again.
	AckStatus_ACK_STATUS_STALE_COMMITMENT AckStatus = 2
	// Entry fails structural validation — a producer-side bug; do not retry
	// unchanged. Structurally invalid: a Record with zero transactions, a
	// commitment or parent-hash field that is not 32 bytes, a base fee that is
	// not minimally encoded or exceeds 32 bytes, a missing entry kind.
	AckStatus_ACK_STATUS_MALFORMED AckStatus = 3
	// Throttled; retry later.
	AckStatus_ACK_STATUS_RATE_LIMITED AckStatus = 4
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_OK",
		2: "ACK_STATUS_STALE_COMMITMENT",
		3: "ACK_STATUS_MALFORMED",
		4: "ACK_STATUS_RATE_LIMITED",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED":      0,
		"ACK_STATUS_OK":               1,
		"ACK_STATUS_STALE_COMMITMENT": 2,
		"ACK_STATUS_MALFORMED":        3,
		"ACK_STATUS_RATE_LIMITED":     4,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sequencestore_v1_sequencestore_proto_enumTypes[0].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_sequencestore_v1_sequencestore_proto_enumTypes[0]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{0}
}

// BlockOpen fixes block N's header context at the moment the producer opens
// it — every header field execution depends on.
type BlockOpen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block being opened (N) — the height the ingress runs the election
	// check at. Carried because a forward-jump
	// re-anchor names a parent the store never saw, so the height is not
	// derivable from store state.
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// N's header timestamp, fixed at open.
	BlockTimestamp uint64 `protobuf:"varint,2,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	// Sealed hash (32 bytes) of the block N builds on — must match a published
	// seal record, or, at cold start / resumption, a canonical block the
	// consumer already has. An open whose parent_hash is not the current tip is
	// a re-anchor.
	ParentHash []byte `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// N's block gas limit — producer-chosen, not derivable from the parent.
	GasLimit uint64 `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// N's base fee as a big-endian unsigned integer, minimally encoded (no
	// leading zero bytes; empty means zero), at most 32 bytes — producer-local
	// policy post-Lisovo, not derivable by consumers.
	BaseFee []byte `protobuf:"bytes,5,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	// The store head this entry extends (32 bytes) — C_seal of the last sealed
	// block on the normal path.
	PrefixCommitment []byte `protobuf:"bytes,6,opt,name=prefix_commitment,json=prefixCommitment,proto3" json:"prefix_commitment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockOpen) Reset() {
	*x = BlockOpen{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOpen) ProtoMessage() {}

func (x *BlockOpen) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOpen.ProtoReflect.Descriptor instead.
func (*BlockOpen) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{0}
}

func (x *BlockOpen) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockOpen) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

func (x *BlockOpen) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockOpen) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *BlockOpen) GetBaseFee() []byte {
	if x != nil {
		return x.BaseFee
	}
	return nil
}

func (x *BlockOpen) GetPrefixCommitment() []byte {
	if x != nil {
		return x.PrefixCommitment
	}
	return nil
}

// Record carries one or more sequenced transactions for the open block,
// never spanning two blocks.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered raw signed transactions (tx hash derivable); one per message for
	// lowest latency, or a batch under load. The commitment chain folds per
	// transaction, so batching does not change the chain. Never empty: every
	// appended entry must advance the head — an empty record would leave two
	// entries at one head, breaking head-as-position — so the ingress rejects
	// it as MALFORMED.
	Transactions [][]byte `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Running head (32 bytes) just before this record's transactions; a block's
	// first record carries C_open(N).
	PrefixCommitment []byte `protobuf:"bytes,2,opt,name=prefix_commitment,json=prefixCommitment,proto3" json:"prefix_commitment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Record) GetPrefixCommitment() []byte {
	if x != nil {
		return x.PrefixCommitment
	}
	return nil
}

// BlockSeal closes block N, appended the moment the block is sealed — after
// N's last record and before N+1's open.
type BlockSeal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// N's full sealed header (RLP); the height is inside the header.
	// keccak256(header) is BLOCKHASH(N) and N+1's parentHash. The header embeds
	// the producer's consensus seal, so it cannot be recomputed from state — it
	// must be delivered. Consumers cross-check their re-execution against its
	// state root, receipts root, and gas used.
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The running head (32 bytes) after N's last transaction, C_block(N) — the
	// seal extends it.
	PrefixCommitment []byte `protobuf:"bytes,2,opt,name=prefix_commitment,json=prefixCommitment,proto3" json:"prefix_commitment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockSeal) Reset() {
	*x = BlockSeal{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSeal) ProtoMessage() {}

func (x *BlockSeal) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSeal.ProtoReflect.Descriptor instead.
func (*BlockSeal) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{2}
}

func (x *BlockSeal) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BlockSeal) GetPrefixCommitment() []byte {
	if x != nil {
		return x.PrefixCommitment
	}
	return nil
}

// Entry is the unit of the stream, published by producers and delivered to
// consumers exactly as published.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Entry_BlockOpen
	//	*Entry_Record
	//	*Entry_BlockSeal
	Kind          isEntry_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetKind() isEntry_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Entry) GetBlockOpen() *BlockOpen {
	if x != nil {
		if x, ok := x.Kind.(*Entry_BlockOpen); ok {
			return x.BlockOpen
		}
	}
	return nil
}

func (x *Entry) GetRecord() *Record {
	if x != nil {
		if x, ok := x.Kind.(*Entry_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *Entry) GetBlockSeal() *BlockSeal {
	if x != nil {
		if x, ok := x.Kind.(*Entry_BlockSeal); ok {
			return x.BlockSeal
		}
	}
	return nil
}

type isEntry_Kind interface {
	isEntry_Kind()
}

type Entry_BlockOpen struct {
	BlockOpen *BlockOpen `protobuf:"bytes,1,opt,name=block_open,json=blockOpen,proto3,oneof"`
}

type Entry_Record struct {
	Record *Record `protobuf:"bytes,2,opt,name=record,proto3,oneof"`
}

type Entry_BlockSeal struct {
	BlockSeal *BlockSeal `protobuf:"bytes,3,opt,name=block_seal,json=blockSeal,proto3,oneof"`
}

func (*Entry_BlockOpen) isEntry_Kind() {}

func (*Entry_Record) isEntry_Kind() {}

func (*Entry_BlockSeal) isEntry_Kind() {}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AckStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=sequencestore.v1.AckStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{5}
}

func (x *PublishResponse) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

// The resume position is exclusive and shared by Stream and Range:
//
//	head  — resumes right after the entry whose post-fold head equals the
//	        value; the consumer presents its own running head, so the stream
//	        continues with exactly what it has not applied, including any
//	        re-anchor entries. Every head value is unique to its position by
//	        construction (this is why the head, not a tx hash, is the resume
//	        token).
//	block — resumes after block n's latest generation (cold start: a fresh
//	        node passes its sealed chain head, then adopts the first entry's
//	        prefix_commitment as its seed). If the latest generation at n is
//	        still open, the position resolves before its open record — the
//	        in-progress generation is served from its start, never from the
//	        middle.
//	unset — from the earliest retained entry.
//
// There is intentionally no latest/live-only value — it would skip the
// entries between a consumer's head and the tip.
type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to After:
	//
	//	*StreamRequest_Head
	//	*StreamRequest_Block
	After         isStreamRequest_After `protobuf_oneof:"after"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{6}
}

func (x *StreamRequest) GetAfter() isStreamRequest_After {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *StreamRequest) GetHead() []byte {
	if x != nil {
		if x, ok := x.After.(*StreamRequest_Head); ok {
			return x.Head
		}
	}
	return nil
}

func (x *StreamRequest) GetBlock() uint64 {
	if x != nil {
		if x, ok := x.After.(*StreamRequest_Block); ok {
			return x.Block
		}
	}
	return 0
}

type isStreamRequest_After interface {
	isStreamRequest_After()
}

type StreamRequest_Head struct {
	Head []byte `protobuf:"bytes,1,opt,name=head,proto3,oneof"`
}

type StreamRequest_Block struct {
	Block uint64 `protobuf:"varint,2,opt,name=block,proto3,oneof"`
}

func (*StreamRequest_Head) isStreamRequest_After() {}

func (*StreamRequest_Block) isStreamRequest_After() {}

type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*StreamResponse_Entry
	//	*StreamResponse_Live
	Frame         isStreamResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{7}
}

func (x *StreamResponse) GetFrame() isStreamResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *StreamResponse) GetEntry() *Entry {
	if x != nil {
		if x, ok := x.Frame.(*StreamResponse_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *StreamResponse) GetLive() *Live {
	if x != nil {
		if x, ok := x.Frame.(*StreamResponse_Live); ok {
			return x.Live
		}
	}
	return nil
}

type isStreamResponse_Frame interface {
	isStreamResponse_Frame()
}

type StreamResponse_Entry struct {
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3,oneof"`
}

type StreamResponse_Live struct {
	Live *Live `protobuf:"bytes,2,opt,name=live,proto3,oneof"`
}

func (*StreamResponse_Entry) isStreamResponse_Frame() {}

func (*StreamResponse_Live) isStreamResponse_Frame() {}

// Live marks that the stream has caught up to the tip; frames after it are
// live entries as they are appended.
type Live struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live) Reset() {
	*x = Live{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live) ProtoMessage() {}

func (x *Live) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live.ProtoReflect.Descriptor instead.
func (*Live) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{8}
}

type RangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to After:
	//
	//	*RangeRequest_Head
	//	*RangeRequest_Block
	After isRangeRequest_After `protobuf_oneof:"after"`
	// Maximum entries in the response; a server default and maximum apply.
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Long-poll budget in milliseconds: if fewer than limit entries are
	// ready, the request is held up to this long for more before returning.
	WaitMs        uint32 `protobuf:"varint,4,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{9}
}

func (x *RangeRequest) GetAfter() isRangeRequest_After {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *RangeRequest) GetHead() []byte {
	if x != nil {
		if x, ok := x.After.(*RangeRequest_Head); ok {
			return x.Head
		}
	}
	return nil
}

func (x *RangeRequest) GetBlock() uint64 {
	if x != nil {
		if x, ok := x.After.(*RangeRequest_Block); ok {
			return x.Block
		}
	}
	return 0
}

func (x *RangeRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RangeRequest) GetWaitMs() uint32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

type isRangeRequest_After interface {
	isRangeRequest_After()
}

type RangeRequest_Head struct {
	Head []byte `protobuf:"bytes,1,opt,name=head,proto3,oneof"`
}

type RangeRequest_Block struct {
	Block uint64 `protobuf:"varint,2,opt,name=block,proto3,oneof"`
}

func (*RangeRequest_Head) isRangeRequest_After() {}

func (*RangeRequest_Block) isRangeRequest_After() {}

type RangeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// The position this response ends at, always valid to pass back as
	// after.head: the post-fold head of the last returned entry, or — when
	// entries is empty — the resolved request position (the presented head, or
	// the post-fold head of block n's latest generation for a block-addressed
	// request).
	Next []byte `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	// True when the response reached the tip.
	Live          bool `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{10}
}

func (x *RangeResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RangeResponse) GetNext() []byte {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *RangeResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlockRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sequencestore_v1_sequencestore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_sequencestore_v1_sequencestore_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlockResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_sequencestore_v1_sequencestore_proto protoreflect.FileDescriptor

const file_sequencestore_v1_sequencestore_proto_rawDesc = "" +
	"\n" +
	"$sequencestore/v1/sequencestore.proto\x12\x10sequencestore.v1\"\xdd\x01\n" +
	"\tBlockOpen\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12'\n" +
	"\x0fblock_timestamp\x18\x02 \x01(\x04R\x0eblockTimestamp\x12\x1f\n" +
	"\vparent_hash\x18\x03 \x01(\fR\n" +
	"parentHash\x12\x1b\n" +
	"\tgas_limit\x18\x04 \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bbase_fee\x18\x05 \x01(\fR\abaseFee\x12+\n" +
	"\x11prefix_commitment\x18\x06 \x01(\fR\x10prefixCommitment\"Y\n" +
	"\x06Record\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\x12+\n" +
	"\x11prefix_commitment\x18\x02 \x01(\fR\x10prefixCommitment\"P\n" +
	"\tBlockSeal\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\x12+\n" +
	"\x11prefix_commitment\x18\x02 \x01(\fR\x10prefixCommitment\"\xbf\x01\n" +
	"\x05Entry\x12<\n" +
	"\n" +
	"block_open\x18\x01 \x01(\v2\x1b.sequencestore.v1.BlockOpenH\x00R\tblockOpen\x122\n" +
	"\x06record\x18\x02 \x01(\v2\x18.sequencestore.v1.RecordH\x00R\x06record\x12<\n" +
	"\n" +
	"block_seal\x18\x03 \x01(\v2\x1b.sequencestore.v1.BlockSealH\x00R\tblockSealB\x06\n" +
	"\x04kind\"?\n" +
	"\x0ePublishRequest\x12-\n" +
	"\x05entry\x18\x01 \x01(\v2\x17.sequencestore.v1.EntryR\x05entry\"F\n" +
	"\x0fPublishResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.sequencestore.v1.AckStatusR\x06status\"F\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x04head\x18\x01 \x01(\fH\x00R\x04head\x12\x16\n" +
	"\x05block\x18\x02 \x01(\x04H\x00R\x05blockB\a\n" +
	"\x05after\"x\n" +
	"\x0eStreamResponse\x12/\n" +
	"\x05entry\x18\x01 \x01(\v2\x17.sequencestore.v1.EntryH\x00R\x05entry\x12,\n" +
	"\x04live\x18\x02 \x01(\v2\x16.sequencestore.v1.LiveH\x00R\x04liveB\a\n" +
	"\x05frame\"\x06\n" +
	"\x04Live\"t\n" +
	"\fRangeRequest\x12\x14\n" +
	"\x04head\x18\x01 \x01(\fH\x00R\x04head\x12\x16\n" +
	"\x05block\x18\x02 \x01(\x04H\x00R\x05block\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x17\n" +
	"\await_ms\x18\x04 \x01(\rR\x06waitMsB\a\n" +
	"\x05after\"j\n" +
	"\rRangeResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.sequencestore.v1.EntryR\aentries\x12\x12\n" +
	"\x04next\x18\x02 \x01(\fR\x04next\x12\x12\n" +
	"\x04live\x18\x03 \x01(\bR\x04live\"4\n" +
	"\x0fGetBlockRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"E\n" +
	"\x10GetBlockResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.sequencestore.v1.EntryR\aentries*\x92\x01\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_STATUS_OK\x10\x01\x12\x1f\n" +
	"\x1bACK_STATUS_STALE_COMMITMENT\x10\x02\x12\x18\n" +
	"\x14ACK_STATUS_MALFORMED\x10\x03\x12\x1b\n" +
	"\x17ACK_STATUS_RATE_LIMITED\x10\x042f\n" +
	"\x10PublisherService\x12R\n" +
	"\aPublish\x12 .sequencestore.v1.PublishRequest\x1a!.sequencestore.v1.PublishResponse(\x010\x012\xfd\x01\n" +
	"\x0fConsumerService\x12M\n" +
	"\x06Stream\x12\x1f.sequencestore.v1.StreamRequest\x1a .sequencestore.v1.StreamResponse0\x01\x12H\n" +
	"\x05Range\x12\x1e.sequencestore.v1.RangeRequest\x1a\x1f.sequencestore.v1.RangeResponse\x12Q\n" +
	"\bGetBlock\x12!.sequencestore.v1.GetBlockRequest\x1a\".sequencestore.v1.GetBlockResponseBLZJgithub.com/0xPolygon/sequence-store-proto/sequencestore/v1;sequencestorev1b\x06proto3"

var (
	file_sequencestore_v1_sequencestore_proto_rawDescOnce sync.Once
	file_sequencestore_v1_sequencestore_proto_rawDescData []byte
)

func file_sequencestore_v1_sequencestore_proto_rawDescGZIP() []byte {
	file_sequencestore_v1_sequencestore_proto_rawDescOnce.Do(func() {
		file_sequencestore_v1_sequencestore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sequencestore_v1_sequencestore_proto_rawDesc), len(file_sequencestore_v1_sequencestore_proto_rawDesc)))
	})
	return file_sequencestore_v1_sequencestore_proto_rawDescData
}

var file_sequencestore_v1_sequencestore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sequencestore_v1_sequencestore_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sequencestore_v1_sequencestore_proto_goTypes = []any{
	(AckStatus)(0),           // 0: sequencestore.v1.AckStatus
	(*BlockOpen)(nil),        // 1: sequencestore.v1.BlockOpen
	(*Record)(nil),           // 2: sequencestore.v1.Record
	(*BlockSeal)(nil),        // 3: sequencestore.v1.BlockSeal
	(*Entry)(nil),            // 4: sequencestore.v1.Entry
	(*PublishRequest)(nil),   // 5: sequencestore.v1.PublishRequest
	(*PublishResponse)(nil),  // 6: sequencestore.v1.PublishResponse
	(*StreamRequest)(nil),    // 7: sequencestore.v1.StreamRequest
	(*StreamResponse)(nil),   // 8: sequencestore.v1.StreamResponse
	(*Live)(nil),             // 9: sequencestore.v1.Live
	(*RangeRequest)(nil),     // 10: sequencestore.v1.RangeRequest
	(*RangeResponse)(nil),    // 11: sequencestore.v1.RangeResponse
	(*GetBlockRequest)(nil),  // 12: sequencestore.v1.GetBlockRequest
	(*GetBlockResponse)(nil), // 13: sequencestore.v1.GetBlockResponse
}
var file_sequencestore_v1_sequencestore_proto_depIdxs = []int32{
	1,  // 0: sequencestore.v1.Entry.block_open:type_name -> sequencestore.v1.BlockOpen
	2,  // 1: sequencestore.v1.Entry.record:type_name -> sequencestore.v1.Record
	3,  // 2: sequencestore.v1.Entry.block_seal:type_name -> sequencestore.v1.BlockSeal
	4,  // 3: sequencestore.v1.PublishRequest.entry:type_name -> sequencestore.v1.Entry
	0,  // 4: sequencestore.v1.PublishResponse.status:type_name -> sequencestore.v1.AckStatus
	4,  // 5: sequencestore.v1.StreamResponse.entry:type_name -> sequencestore.v1.Entry
	9,  // 6: sequencestore.v1.StreamResponse.live:type_name -> sequencestore.v1.Live
	4,  // 7: sequencestore.v1.RangeResponse.entries:type_name -> sequencestore.v1.Entry
	4,  // 8: sequencestore.v1.GetBlockResponse.entries:type_name -> sequencestore.v1.Entry
	5,  // 9: sequencestore.v1.PublisherService.Publish:input_type -> sequencestore.v1.PublishRequest
	7,  // 10: sequencestore.v1.ConsumerService.Stream:input_type -> sequencestore.v1.StreamRequest
	10, // 11: sequencestore.v1.ConsumerService.Range:input_type -> sequencestore.v1.RangeRequest
	12, // 12: sequencestore.v1.ConsumerService.GetBlock:input_type -> sequencestore.v1.GetBlockRequest
	6,  // 13: sequencestore.v1.PublisherService.Publish:output_type -> sequencestore.v1.PublishResponse
	8,  // 14: sequencestore.v1.ConsumerService.Stream:output_type -> sequencestore.v1.StreamResponse
	11, // 15: sequencestore.v1.ConsumerService.Range:output_type -> sequencestore.v1.RangeResponse
	13, // 16: sequencestore.v1.ConsumerService.GetBlock:output_type -> sequencestore.v1.GetBlockResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_sequencestore_v1_sequencestore_proto_init() }
func file_sequencestore_v1_sequencestore_proto_init() {
	if File_sequencestore_v1_sequencestore_proto != nil {
		return
	}
	file_sequencestore_v1_sequencestore_proto_msgTypes[3].OneofWrappers = []any{
		(*Entry_BlockOpen)(nil),
		(*Entry_Record)(nil),
		(*Entry_BlockSeal)(nil),
	}
	file_sequencestore_v1_sequencestore_proto_msgTypes[6].OneofWrappers = []any{
		(*StreamRequest_Head)(nil),
		(*StreamRequest_Block)(nil),
	}
	file_sequencestore_v1_sequencestore_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamResponse_Entry)(nil),
		(*StreamResponse_Live)(nil),
	}
	file_sequencestore_v1_sequencestore_proto_msgTypes[9].OneofWrappers = []any{
		(*RangeRequest_Head)(nil),
		(*RangeRequest_Block)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sequencestore_v1_sequencestore_proto_rawDesc), len(file_sequencestore_v1_sequencestore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sequencestore_v1_sequencestore_proto_goTypes,
		DependencyIndexes: file_sequencestore_v1_sequencestore_proto_depIdxs,
		EnumInfos:         file_sequencestore_v1_sequencestore_proto_enumTypes,
		MessageInfos:      file_sequencestore_v1_sequencestore_proto_msgTypes,
	}.Build()
	File_sequencestore_v1_sequencestore_proto = out.File
	file_sequencestore_v1_sequencestore_proto_goTypes = nil
	file_sequencestore_v1_sequencestore_proto_depIdxs = nil
}
