// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: sequencestore/v1/sequencestore.proto

package sequencestorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublisherService_Publish_FullMethodName = "/sequencestore.v1.PublisherService/Publish"
)

// PublisherServiceClient is the client API for PublisherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PublisherService is the producer → ingress write path: internal, trusted,
// latency-sensitive. The channel is authenticated (per-validator credential);
// producers are never declared in requests — write access is the credential,
// and the head check arbitrates concurrent writers onto one chain. There is
// no tail-fetch call here: on takeover or after a rejection the producer
// reads the stream to the tip via ConsumerService and re-applies what it
// missed.
type PublisherServiceClient interface {
	// Publish pipelines entries and returns one ack per entry, in the order the
	// entries were received. A non-OK ack does not close the stream, but every
	// entry pipelined behind a rejected one fails the head check too
	// (STALE_COMMITMENT) — on any rejection the producer stops, resyncs, and
	// resumes.
	Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error)
}

type publisherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublisherServiceClient(cc grpc.ClientConnInterface) PublisherServiceClient {
	return &publisherServiceClient{cc}
}

func (c *publisherServiceClient) Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PublisherService_ServiceDesc.Streams[0], PublisherService_Publish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishRequest, PublishResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PublisherService_PublishClient = grpc.BidiStreamingClient[PublishRequest, PublishResponse]

// PublisherServiceServer is the server API for PublisherService service.
// All implementations must embed UnimplementedPublisherServiceServer
// for forward compatibility.
//
// PublisherService is the producer → ingress write path: internal, trusted,
// latency-sensitive. The channel is authenticated (per-validator credential);
// producers are never declared in requests — write access is the credential,
// and the head check arbitrates concurrent writers onto one chain. There is
// no tail-fetch call here: on takeover or after a rejection the producer
// reads the stream to the tip via ConsumerService and re-applies what it
// missed.
type PublisherServiceServer interface {
	// Publish pipelines entries and returns one ack per entry, in the order the
	// entries were received. A non-OK ack does not close the stream, but every
	// entry pipelined behind a rejected one fails the head check too
	// (STALE_COMMITMENT) — on any rejection the producer stops, resyncs, and
	// resumes.
	Publish(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error
	mustEmbedUnimplementedPublisherServiceServer()
}

// UnimplementedPublisherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublisherServiceServer struct{}

func (UnimplementedPublisherServiceServer) Publish(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error {
	return status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPublisherServiceServer) mustEmbedUnimplementedPublisherServiceServer() {}
func (UnimplementedPublisherServiceServer) testEmbeddedByValue()                          {}

// UnsafePublisherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublisherServiceServer will
// result in compilation errors.
type UnsafePublisherServiceServer interface {
	mustEmbedUnimplementedPublisherServiceServer()
}

func RegisterPublisherServiceServer(s grpc.ServiceRegistrar, srv PublisherServiceServer) {
	// If the following call panics, it indicates UnimplementedPublisherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublisherService_ServiceDesc, srv)
}

func _PublisherService_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PublisherServiceServer).Publish(&grpc.GenericServerStream[PublishRequest, PublishResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PublisherService_PublishServer = grpc.BidiStreamingServer[PublishRequest, PublishResponse]

// PublisherService_ServiceDesc is the grpc.ServiceDesc for PublisherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublisherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sequencestore.v1.PublisherService",
	HandlerType: (*PublisherServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _PublisherService_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sequencestore/v1/sequencestore.proto",
}

const (
	ConsumerService_Stream_FullMethodName   = "/sequencestore.v1.ConsumerService/Stream"
	ConsumerService_Range_FullMethodName    = "/sequencestore.v1.ConsumerService/Range"
	ConsumerService_GetBlock_FullMethodName = "/sequencestore.v1.ConsumerService/GetBlock"
)

// ConsumerServiceClient is the client API for ConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConsumerService is the store → consumer read path, served through the
// egress gateway: untrusted-facing, per-connection authenticated. Entries are
// delivered exactly as published; pre-seal content is attributed by trusting
// the store's authenticated ingress. Consumers verify chain integrity
// themselves (prefix continuity, seal cross-checks); the store is not a
// chain validator.
type ConsumerServiceClient interface {
	// Stream delivers entries from the requested position to the tip, then
	// stays open for live entries. A Live frame marks the caught-up-to-tip
	// transition. An aged-out or unknown resume head fails with NOT_FOUND — the
	// consumer falls back to its block anchor.
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	// Range is the pull counterpart of Stream: up to limit entries after the
	// requested position, with an optional long-poll budget. Same resume
	// semantics as Stream, including NOT_FOUND for an aged-out or unknown
	// position.
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error)
	// GetBlock fetches block n's entries — its BlockOpen, its Records, and its
	// BlockSeal once sealed (inclusive fetch). Block-addressed reads resolve to
	// the latest generation at that height. An unknown or unretained height
	// fails with NOT_FOUND.
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
}

type consumerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerServiceClient(cc grpc.ClientConnInterface) ConsumerServiceClient {
	return &consumerServiceClient{cc}
}

func (c *consumerServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsumerService_ServiceDesc.Streams[0], ConsumerService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsumerService_StreamClient = grpc.ServerStreamingClient[StreamResponse]

func (c *consumerServiceClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeResponse)
	err := c.cc.Invoke(ctx, ConsumerService_Range_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, ConsumerService_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServiceServer is the server API for ConsumerService service.
// All implementations must embed UnimplementedConsumerServiceServer
// for forward compatibility.
//
// ConsumerService is the store → consumer read path, served through the
// egress gateway: untrusted-facing, per-connection authenticated. Entries are
// delivered exactly as published; pre-seal content is attributed by trusting
// the store's authenticated ingress. Consumers verify chain integrity
// themselves (prefix continuity, seal cross-checks); the store is not a
// chain validator.
type ConsumerServiceServer interface {
	// Stream delivers entries from the requested position to the tip, then
	// stays open for live entries. A Live frame marks the caught-up-to-tip
	// transition. An aged-out or unknown resume head fails with NOT_FOUND — the
	// consumer falls back to its block anchor.
	Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	// Range is the pull counterpart of Stream: up to limit entries after the
	// requested position, with an optional long-poll budget. Same resume
	// semantics as Stream, including NOT_FOUND for an aged-out or unknown
	// position.
	Range(context.Context, *RangeRequest) (*RangeResponse, error)
	// GetBlock fetches block n's entries — its BlockOpen, its Records, and its
	// BlockSeal once sealed (inclusive fetch). Block-addressed reads resolve to
	// the latest generation at that height. An unknown or unretained height
	// fails with NOT_FOUND.
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	mustEmbedUnimplementedConsumerServiceServer()
}

// UnimplementedConsumerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumerServiceServer struct{}

func (UnimplementedConsumerServiceServer) Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedConsumerServiceServer) Range(context.Context, *RangeRequest) (*RangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Range not implemented")
}
func (UnimplementedConsumerServiceServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedConsumerServiceServer) mustEmbedUnimplementedConsumerServiceServer() {}
func (UnimplementedConsumerServiceServer) testEmbeddedByValue()                         {}

// UnsafeConsumerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServiceServer will
// result in compilation errors.
type UnsafeConsumerServiceServer interface {
	mustEmbedUnimplementedConsumerServiceServer()
}

func RegisterConsumerServiceServer(s grpc.ServiceRegistrar, srv ConsumerServiceServer) {
	// If the following call panics, it indicates UnimplementedConsumerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsumerService_ServiceDesc, srv)
}

func _ConsumerService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServiceServer).Stream(m, &grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsumerService_StreamServer = grpc.ServerStreamingServer[StreamResponse]

func _ConsumerService_Range_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).Range(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerService_Range_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).Range(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsumerService_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsumerService_ServiceDesc is the grpc.ServiceDesc for ConsumerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsumerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sequencestore.v1.ConsumerService",
	HandlerType: (*ConsumerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Range",
			Handler:    _ConsumerService_Range_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _ConsumerService_GetBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ConsumerService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sequencestore/v1/sequencestore.proto",
}
